language: python
python:
  - "3.6"
  
dist: xenial
services:
  - xvfb
 
addons:
  ssh_known_hosts: frs.sourceforge.net
  # ---------------------------------------------------------------
  # Now use APT to install metacity, which is a window manager also 
  # needed for the SWTBOT UI tests
  # ---------------------------------------------------------------
  apt:
    sources:
    - sourceline: "ppa:freecad-maintainers/freecad-stable"
    packages:
    - metacity
    - freecad

install:
- true 

stages:
# ------------------------------------
# Just one stage, multiple stages 
# with maven overcomplicate the things
# ------------------------------------
- name: verify
- name: test
- name: assemble-deploy

env:
  global:
  - VERSION=4.9.0
  - A2PLUS_REPO=https://github.com/kbwbe/A2plus
  - A2PLUS_VERSION=v0.4.26
  # ---------------------------------------------
  # API Token for access to github
  # ---------------------------------------------
  - secure: "EjN6DgVHJ8urI5vaahXVx0bBkA5pKVnoNJQUM0R7QMj14BNz+zmLamdFTjqjBY0BGxATd+qyTJLy/Eo/lqGzHhU0XNvKlXee8fn3d7k74kupK4kf/j997b8LQarXph3NhK8pr5sTzPpnutvbJ42VraVAkRBI46CKwaQoS/+W1NkZbAmcd19rnn18Mu69RdQRa/qLXfOvbptO9dIOZiz/chEBmuYJcsMy55We6BNcc2U1ubofNhqsVKnEvzukPAGdOxfqt1pWuoMb6FoY/RJhFmBJ7qeqdnPRkDMUJVcwPSET5bi+t+Sla3TWzfvzacprx6TjB5mYIN4Lkjdu6ZS0BD8mBTojFs4waQnGnjlqyBG5TyHDtzNiztYhOK3QROngyuTvebLZ7Nvvy9lpSQdGspAou/u650ZlfBFOptv9r7VQ95wipmwRKZenT8y1yhNpsDXAxEaDK7bS/RyuqJiMsnDpQEFaXxM8SrgFzT3Ne/FGEwbVgeKhJBAlf7okBfHwqaTHA1fCwaqJJ/ADB2GKok+cvLYienWxoGrZD2mmmBFGhY8+F0hoMpIIS2dKHa6CXE3aUOx2g8iJ5xDow3Z7mKQLxqPRvLlne9uL67SUylTrixWKRt20+ZixXeg+NkwnFmKlfrD6jn/7PA8RxxhrgltkAWrRX0C35HBZTDIgMxg="

before_script:
  # -----------------------------------
  # Startup the metacity window manager
  # -----------------------------------
  - metacity --sm-disable --replace 2> metacity.err &
  
jobs:
  include:
    # --------------------------------------------
    # Run a quicksanity check if all commits are
    # handed in by known users
    #---------------------------------------------
    - stage: verify
      if: branch NOT IN (integration_snapshot, development_snapshot) 
      name: Verify - Authors Sanity Check
      script:
      - ./bash/verify_commit_authors.sh known_authors.txt
  
    # -----------------------------------------------------
    # Build and Test - SpotBugs Jobs
    # -----------------------------------------------------
    - stage: test
      if: branch NOT IN (integration_snapshot, development_snapshot) 
      name: Test - FreeCAD Module Tests
      script:
      # Install A2plus dependency to FreeCAD
      - curl -L --create-dirs -o ~/.FreeCad/Mod/a2plus.tar.gz ${A2PLUS_REPO}/archive/${A2PLUS_VERSION}.tar.gz
      - tar -zxf ~/.FreeCad/Mod/a2plus.tar.gz -C ~/.FreeCAD/Mod/^
      # Execute FreeCAD tests
      - freecad -M $(pwd) -t TestVirtualSatelliteApp
      
    - stage: test
      if: branch NOT IN (integration_snapshot, development_snapshot) 
      name: Test - FreeCAD Module flake8
      script:
      - python3 -m pip install flake8
      - flake8 . --count --show-source --statistics
      
    - stage: test
      if: branch NOT IN (integration_snapshot, development_snapshot) 
      name: Test - FreeCAD All Tests
      script:
      # Install A2plus dependency to FreeCAD
      - curl -L --create-dirs -o ~/.FreeCad/Mod/a2plus.tar.gz ${A2PLUS_REPO}/archive/${A2PLUS_VERSION}.tar.gz
      - tar -zxf ~/.FreeCad/Mod/a2plus.tar.gz -C ~/.FreeCAD/Mod/^
      # Execute FreeCAD tests
      - freecad -M $(pwd) -t 0

    # -----------------------------------------------------------
    # Deploy Jobs for unsecured Development.
    #------------------------------------------------------------
    - stage: assemble-deploy
      if: branch = development
      name: Assemble-Deploy - Development
      script:
      - echo "Version ${VERSION} (Build $(date +"%Y%m%d%H%M%S"d)-${TRAVIS_BUILD_NUMBER})" > BUILD.txt
      - pushd .
      - cd ..  
      - zip -r VirtualSatellite4_FreeCAD_mod_Development.zip VirtualSatellite4-FreeCAD-mod -x "*/.*"
      - tar --exclude="*/.*" -czvf VirtualSatellite4_FreeCAD_mod_Development.tar.gz VirtualSatellite4-FreeCAD-mod
      - popd 
      before_deploy:
        # -----------------------------------------------------------
        # Update the development tag beforehand
        # And send it back to the origin, otherwise travis will 
        # apparently perform a git fetch before, and overwrite the
        # moved tag back to the previous state.
        #------------------------------------------------------------
        - git tag -f development_snapshot
        - git remote add github-mtd  https://${GITHUB_API_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git
        - git push -f github-mtd development_snapshot
        - git remote remove github-mtd
      deploy:
        # -----------------------------------------------------------
        # Now attach the release to the newly created tag.
        # release is attached to the tag on the current commit.
        # -----------------------------------------------------------
      - provider: releases
        api_key: $GITHUB_API_TOKEN
        file_glob: true
        file:
        - ../*.zip
        - ../*.tar.gz
        skip_cleanup: true
        name: Virtual Satellite 4 FreeCAD mod Development Build
        body: Development build on latest commit by Travis CI - $TRAVIS_BRANCH ($TRAVIS_COMMIT) - $(date +'%F %T %Z'). This release is subject to constant change.
        prerelease: true
        overwrite: true
        target_commitish: $TRAVIS_COMMIT
        on:
          repo: virtualsatellite/VirtualSatellite4-FreeCAD-mod
          branch: development
      
    # -----------------------------------------------------------
    # Deploy Jobs for unsecured Integration.
    #------------------------------------------------------------
    - stage: assemble-deploy
      if: branch = integration
      name: Assemble-Deploy - Integration
      script:
      - echo "Version ${VERSION} (Build $(date +"%Y%m%d%H%M%S"i)-${TRAVIS_BUILD_NUMBER})" > BUILD.txt  
      - pushd .
      - cd ..
      - zip -r VirtualSatellite4_FreeCAD_mod_Integration_${VERSION}.zip VirtualSatellite4-FreeCAD-mod -x "*/.*"
      - tar --exclude="*/.*" -czvf VirtualSatellite4_FreeCAD_mod_Integration_${VERSION}.tar.gz VirtualSatellite4-FreeCAD-mod
      - popd
      before_deploy:
        # -----------------------------------------------------------
        # Update the development tag beforehand
        # And send it back to the origin, otherwise travis will 
        # apparently perform a git fetch before, and overwrite the
        # moved tag back to the previous state.
        #------------------------------------------------------------
        - git tag -f integration_snapshot
        - git remote add github-mtd  https://${GITHUB_API_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git
        - git push -f github-mtd integration_snapshot
        - git remote remove github-mtd
      deploy:
        # -----------------------------------------------------------
        # Now attach the release to the newly created tag.
        # release is attached to the tag on the current commit.
        # -----------------------------------------------------------
      - provider: releases
        api_key: $GITHUB_API_TOKEN
        file_glob: true
        file: 
        - ../*.zip
        - ../*.tar.gz
        skip_cleanup: true
        name: Virtual Satellite 4 FreeCAD mod Integration Build
        body: Integration build on latest commit by Travis CI - $TRAVIS_BRANCH ($TRAVIS_COMMIT) - $(date +'%F %T %Z'). This release is subject to constant change.
        prerelease: true
        overwrite: true
        target_commitish: $TRAVIS_COMMIT
        on:
          repo: virtualsatellite/VirtualSatellite4-FreeCAD-mod
          branch: integration
    
    # -----------------------------------------------------------
    # Deploy Jobs for secured Releases.
    #------------------------------------------------------------
    - stage: assemble-deploy
      if: tag =~ /^Release/
      name: Assemble-Deploy - Release
      script:
      - echo "Version ${VERSION} (Build $(date +"%Y%m%d%H%M%S"r)-${TRAVIS_BUILD_NUMBER})" > BUILD.txt
      - pushd .
      - cd ..  
      - zip -r VirtualSatellite4_FreeCAD_mod_Release_${VERSION}_${TRAVIS_BUILD_NUMBER}.zip VirtualSatellite4-FreeCAD-mod -x "*/.*"
      - tar --exclude="*/.*" -czvf VirtualSatellite4_FreeCAD_mod_Release_${VERSION}_${TRAVIS_BUILD_NUMBER}.tar.gz VirtualSatellite4-FreeCAD-mod
      - popd
      deploy:
        # -----------------------------------------------------------
        # Now attach the release to the Release Tag.
        # -----------------------------------------------------------
      - provider: releases
        api_key: $GITHUB_API_TOKEN
        file_glob: true
        file: 
        - ../*.zip
        - ../*.tar.gz
        skip_cleanup: true
        name: Virtual Satellite 4 FreeCAD mod Release Build
        body: Release build on latest commit by Travis CI - $TRAVIS_BRANCH ($TRAVIS_COMMIT) - $(date +'%F %T %Z'). This is a stable release.
        prerelease: true
        on:
          repo: virtualsatellite/VirtualSatellite4-FreeCAD-mod
          tags: true
                    